version: '3.2'

services:
  db:
    image: postgres:10.1
    container_name: google-parser_db
    environment:
      - POSTGRES_DB=google-parser_production
    ports:
      - "5432:5432"

  redis:
    image: redis:4.0.9
    container_name: google-parser_redis
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      cache_from:
        - ${DOCKER_IMAGE}:${BRANCH_TAG}
      args:
        - RUBY_ENV=production
        - NODE_ENV=production
        - BUILD_ENV=production
        - ASSET_HOST=http://athena.nimbl3.com
    image: ${DOCKER_IMAGE}:${BRANCH_TAG}
    container_name: google-parser_web
    command: bin/start.sh
    ports:
      - "${PORT}:${PORT}"
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - "ruby-bundle:/bundle"
    environment:
      - RACK_ENV=production
      - RAILS_ENV=production
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres@db/google-parser_production
      - ASSET_HOST=
      - DEFAULT_HOST=
      - MAILER_SENDER=
      - RAILS_MASTER_KEY=

volumes:
  ruby-bundle:
