default: &default
  DB_NAME: "google-parser"
  DB_HOST: "localhost"
  DB_PORT: "5432"
  USERNAME: "postgres"
  MAILER_DEFAULT_HOST: "localhost"
  MAILER_DEFAULT_PORT: "3000"
  MAILER_SENDER: "Test <noreply@nimbl3.co>"

development:
  <<: *default

test:
  <<: *default
  TEST_RETRY: "0"
